// Autogenerated by Thrift Compiler (0.13.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package ncbaseheader

import (
	"bytes"
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"reflect"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

const NC_EPMS_CONNECT_MSG = "msg://epms/system/connect"
const NC_EPMS_HEARTBEAT_MSG = "msg://epms/system/heartbeat"
const NC_EPMS_DISCONNECT_MSG = "msg://epms/system/disconnect"

func init() {
}
